### This notebook is to pull data from panorama API's for a given constraint's flow and decomposition by outage, fuel type etc.
It only works for one constraint at a time. In the appropriate cell below, we have to enter the da oops constraint num, and start and end date of the se flows we want to read

In [1]:
import requests
import pandas as pd
import io

import sys
sys.path.append("/var/www/python/Prod/nighthawk")
from nighthawk.util.sql_functions import download_df_from_sql_db
import plotly.express as px

def _get_panorama_data(api_= "", func_path_ = "", method=requests.get, payload = None):
    api_roots = {"reflow" : 'https://api1.marginalunit.com/reflow', 
                 "rms" : 'https://api1.marginalunit.com/rms', 
                 "constraintdb" : 'https://api1.marginalunit.com/constraintdb'}
    url = api_roots[api_] + func_path_
    print(url)
    
    username = "dilip@grgenergy.com"
    password = "6%lUXz^W7DWN"
    AUTH = (username, password)

    resp = method(url = url, auth=AUTH, params=payload)
    if resp.status_code != 200:
        print(resp.text)
    resp.raise_for_status()
    return pd.read_csv(io.StringIO(resp.text))

def get_panorama_all_constraints(iso):
    payload = {"iso":iso,
          "uid_mode":"logical",
          }
    return _get_panorama_data("constraintdb", "/spp/constraints", requests.get, payload)

all_spp_constraints = get_panorama_all_constraints("spp")

https://api1.marginalunit.com/constraintdb/spp/constraints

In [2]:
all_spp_constraints

,monitored_uid,contingency_uid,iso_constraint_labels,monitored_label,contingency_label,da_shadow_price_sum,da_bind_count,rt_shadow_price_sum,rt_bind_count,earliest_appearance,latest_appearance,monitored_label_short,baa
0,"10112A_LN@DOBSON<10428>,LN DOBSON - MORRIS3,NEG,E",SECI:IRSKDOL3 GRDNCT1:115:3:10,10112A_LN@DOBSON<10428>,LN DOBSON - MORRIS3,SECI:IRSKDOL3 GRDNCT1:115:3:10,39.50,11.0,0.00,0.00,2020-05-09 21:00:00-05:00,2020-05-20 20:00:00-05:00,LN DOBSON - MORRIS3,SPP
1,"10112A_LN@DOBSON<6055>,LN DOBSON - MORRIS3,NEG,E",LN HOLCOM1 - GRDNCT1 115 SECI,10112A_LN@DOBSON<6055>,LN DOBSON - MORRIS3,LN HOLCOM1 - GRDNCT1 115 SECI,8.39,4.0,0.00,0.00,2019-10-26 00:00:00-05:00,2019-10-26 03:00:00-05:00,LN DOBSON - MORRIS3,SPP
2,"10112A_LN@DOBSON<BASE>,LN DOBSON - MORRIS3,NEG,E",BASE,10112A_LN@DOBSON<BASE>,LN DOBSON - MORRIS3,BASE,30.97,13.0,0.00,0.00,2015-10-01 05:00:00-05:00,2015-10-12 20:00:00-05:00,LN DOBSON - MORRIS3,SPP
3,"1016AB_XF@HOLCOM1<CON3203>,XFMR HOLCOM1 - HOLC...",LN CRKCREEK-CUDAHY1 A 115 SECI,1016AB_XF@HOLCOM1<CON3203>,XFMR HOLCOM1 - HOLCOM1,LN CRKCREEK-CUDAHY1 A 115 SECI,119.72,6.0,0.00,0.00,2017-04-23 19:00:00-05:00,2017-04-24 10:00:00-05:00,XFMR HOLCOM1 - HOLCOM1,SPP
4,"1016AB_XF@HOLCOM1<CON576>,XFMR HOLCOM1 - HOLCO...",LN BUCKNER7-SPERVI1 A 345 SECI,1016AB_XF@HOLCOM1<CON576>,XFMR HOLCOM1 - HOLCOM1,LN BUCKNER7-SPERVI1 A 345 SECI,815.23,54.0,0.00,0.00,2017-11-10 21:00:00-06:00,2017-12-03 23:00:00-06:00,XFMR HOLCOM1 - HOLCOM1,SPP
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10756,"YUKON 8710 A LN,MSTNG1,69.0,YUKON,69.0",LN MUSTANG - MACARTHUR 69 KV OKGE,TMP407_24471,LN MSTNG1 69KV - YUKON 69KV (YUKON 8710 A LN),LN MUSTANG - MACARTHUR 69 KV OKGE,0.00,0.0,0.00,0.00,2019-01-16 08:35:00-06:00,2019-01-17 00:10:00-06:00,LN MSTNG1 69KV - YUKON 69KV,SPP
10757,"YUKON 8710 A LN,MSTNG1,69.0,YUKON,69.0",OKGE:MSTNG1:138 69:1:11,TMP217_27575,LN MSTNG1 69KV - YUKON 69KV (YUKON 8710 A LN),OKGE:MSTNG1:138 69:1:11,0.00,0.0,92.04,6.33,2022-04-14 04:40:00-05:00,2022-04-15 20:35:00-05:00,LN MSTNG1 69KV - YUKON 69KV,SPP
10758,"ZACH TR1 TR1 XF,ZACH,345.0,ZACH,161.0",AMRN MEC:MYWD ZACH SUB_T:345:3:17,TMP681_28249,XF ZACH 345KV - ZACH 161KV (ZACH TR1 TR1 XF),AMRN MEC:MYWD ZACH SUB_T:345:3:17,0.00,0.0,8554.59,9.58,2022-12-23 10:25:00-06:00,2022-12-28 01:15:00-06:00,XF ZACH 345KV - ZACH 161KV,SPP
10759,"ZACH ZACH_ADIR_7671 A LN,ZACH,161.0,ADIR,161.0",AMRN MEC:MYWD ZACH SUB_T:345:3:17,TMP920_29131,LN ZACH 161KV - ADIR 161KV (ZACH ZACH_ADIR_767...,AMRN MEC:MYWD ZACH SUB_T:345:3:17,278.30,4.0,10233.89,86.50,2023-12-19 04:30:00-06:00,2024-01-02 06:05:00-06:00,LN ZACH 161KV - ADIR 161KV,SPP
10760,"ZACH ZACH_ADIR_7671 A LN,ZACH,161.0,ADIR,161.0",AMRN:MYWD ZACH:345:1:5,TMP920_29131,LN ZACH 161KV - ADIR 161KV (ZACH ZACH_ADIR_767...,AMRN:MYWD ZACH:345:1:5,0.00,0.0,3980.46,36.00,2024-01-08 06:15:00-06:00,2024-01-21 09:05:00-06:00,LN ZACH 161KV - ADIR 161KV,SPP

In [3]:
def get_panorama_constraint_uids(da_oops_con_num):
    SPP_ID = download_df_from_sql_db(f"select ConstraintName from spp_constraints.ConstraintNameAndDetails_v3 where constraintNum = {da_oops_con_num}").iloc[0,0]    
    (SPP_ID)
    con_details = all_spp_constraints[all_spp_constraints["iso_constraint_labels"].str.contains(SPP_ID)].to_dict(orient='records')[0]
    # print(con_details)
    return con_details['monitored_uid'], con_details['contingency_uid']

In [4]:
def get_outage_decomposition(mon_uid, con_uid, start_dt, end_dt):
    path_ = f"/spp-se/constraint/outage_decomposition"
    payload = {"collection" : "spp-se",
              "monitored_uid" : mon_uid,
              "contingency_uid" : con_uid,
              "start_datetime" : start_dt,
              "end_datetime" : end_dt}
    return _get_panorama_data("reflow", path_, requests.get, payload)

In [5]:
#Enter constraint da oops constraint number here. Also enter date range in which to pull data
#Note panorama doesn't seem to give outage decomposition for all oops cons num for a given constraint. 
# SO sometimes have to try multiple oops constrait nums in the same family

oops_con_num = 770216
# SPP_ID = download_df_from_sql_db(f"select ConstraintName from spp_constraints.ConstraintNameAndDetails_v3 where constraintNum = {oops_con_num}").iloc[0,0] 
# print(SPP_ID)
# con_details = all_spp_constraints[all_spp_constraints["iso_constraint_labels"].str.contains(SPP_ID)].to_dict(orient='records')[0]
# print(con_details)
# x = all_spp_constraints.loc[all_spp_constraints['monitored_label'].str.contains('HOBB'),'iso_constraint_labels'] #.sort_values('da_shadow_price_sum', ascending = False)
# print(x)
mon_uid, con_uid = get_panorama_constraint_uids(oops_con_num)
print(mon_uid,'\n',con_uid)
# mon_uid = "10112A_LN@DOBSON<10428>,LN DOBSON - MORRIS3,NEG"
# con_uid = "SECI:IRSKDOL3 GRDNCT1:115:3:10"
start_dte = '2025-01-01'
end_dte = '2026-03-31'

TERRY_CO 161 1 LN,WOLFFORT,115.0,TERRY_CO,115.0
 SPS:YOAKUM TUCO:345:1:12

In [6]:
all_spp_constraints[all_spp_constraints['monitored_label'].str.contains('59TH')].sort_values('da_shadow_price_sum', ascending = False)

,monitored_uid,contingency_uid,iso_constraint_labels,monitored_label,contingency_label,da_shadow_price_sum,da_bind_count,rt_shadow_price_sum,rt_bind_count,earliest_appearance,latest_appearance,monitored_label_short,baa
166,"59TH ELPAMURR13_1 A LN,59TH,138.0,ELPA,138.0",LN BENT - WICH 345kV WR,"ELPAMURR13_1A_LN@59TH<11777>,TMP951_32303",LN 59TH 138KV - ELPA 138KV (59TH ELPAMURR13_1 ...,LN BENT - WICH 345kV WR,66495.43,460.0,62683.64,219.75,2022-10-15 23:00:00-05:00,2026-04-28 00:00:00-05:00,LN 59TH 138KV - ELPA 138KV,SPP
168,"59TH ELPAMURR13_1 A LN,59TH,138.0,ELPA,138.0",LN WDRNG1 - WICH 345kV OKGE,"TMP747_32476,TP1320_32875",LN 59TH 138KV - ELPA 138KV (59TH ELPAMURR13_1 ...,LN WDRNG1 - WICH 345kV OKGE,24585.28,132.0,5749.15,30.33,2025-11-25 10:10:00-06:00,2026-04-10 04:50:00-05:00,LN 59TH 138KV - ELPA 138KV,SPP
173,"59TH ELPAMURR13_1 A LN,ELPA,138.0,59TH,138.0",LN 45TH_ST-GORD 138KV WR,"ELPAMURR13_1A_LN@59TH<CON3953>,TEMP30_19889",LN ELPA 138KV - 59TH 138KV (59TH ELPAMURR13_1 ...,LN 45TH_ST-GORD 138KV WR,17113.30,103.0,16455.95,14.83,2014-01-08 09:00:00-06:00,2016-08-06 15:00:00-05:00,LN ELPA 138KV - 59TH 138KV,SPP
169,"59TH ELPAMURR13_1 A LN,59TH,138.0,ELPA,138.0",WR:MAIZ GORD:138:1:4,"ELPAMURR13_1A_LN@59TH<14428>,TMP863_32465",LN 59TH 138KV - ELPA 138KV (59TH ELPAMURR13_1 ...,WR:MAIZ GORD:138:1:4,16446.81,85.0,790.06,3.67,2025-11-17 07:00:00-06:00,2026-03-17 10:00:00-05:00,LN 59TH 138KV - ELPA 138KV,SPP
171,"59TH ELPAMURR13_1 A LN,59TH,138.0,ELPA,138.0",WR:WOLF UN 15:25:1:2,TMP971_32491,LN 59TH 138KV - ELPA 138KV (59TH ELPAMURR13_1 ...,WR:WOLF UN 15:25:1:2,15788.87,41.0,45741.22,112.17,2025-12-02 13:15:00-06:00,2026-04-10 05:10:00-05:00,LN 59TH 138KV - ELPA 138KV,SPP
172,"59TH ELPAMURR13_1 A LN,59TH,138.0,ELPA,138.0",WR:WOLF:25:1:2,TMP971_32491,LN 59TH 138KV - ELPA 138KV (59TH ELPAMURR13_1 ...,WR:WOLF:25:1:2,10434.75,49.0,56.51,0.08,2026-04-06 18:55:00-05:00,2026-04-10 00:00:00-05:00,LN 59TH 138KV - ELPA 138KV,SPP
167,"59TH ELPAMURR13_1 A LN,59TH,138.0,ELPA,138.0",LN RENFROW7-VIOLA7 A 345 WR,"ELPAMURR13_1A_LN@59TH<16357>,TP1115_32495",LN 59TH 138KV - ELPA 138KV (59TH ELPAMURR13_1 ...,LN RENFROW7-VIOLA7 A 345 WR,9082.07,44.0,4768.62,13.58,2025-11-23 21:00:00-06:00,2025-12-19 01:20:00-06:00,LN 59TH 138KV - ELPA 138KV,SPP
177,"59TH ELPAMURR13_1 B LN,59TH,138.0,MURR,138.0",LN 45TH_ST-GORD 138KV WR,"MA_ELPAMURR13,TEMP30_19889,TEMP40_21835",LN 59TH 138KV - MURR 138KV (59TH ELPAMURR13_1 ...,LN 45TH_ST-GORD 138KV WR,3173.17,23.0,0.00,0.00,2014-02-24 07:00:00-06:00,2016-06-22 15:00:00-05:00,LN 59TH 138KV - MURR 138KV,SPP
180,"59TH ELPAMURR13_1 B LN,MURR,138.0,59TH,138.0",LN BENT - WICH 345kV WR,"ELPAMURR13_1B_LN@59TH<CON1624>,TMP144_25283",LN MURR 138KV - 59TH 138KV (59TH ELPAMURR13_1 ...,LN BENT - WICH 345kV WR,2022.23,22.0,0.00,0.00,2019-10-09 13:00:00-05:00,2019-11-07 09:00:00-06:00,LN MURR 138KV - 59TH 138KV,SPP
175,"59TH ELPAMURR13_1 A LN,ELPA,138.0,59TH,138.0",XF WICH WICH_11 345/138 WR,"ELPAMURR13_1A_LN@59TH<CON1839>,TMP160_23220",LN ELPA 138KV - 59TH 138KV (59TH ELPAMURR13_1 ...,XF WICH WICH_11 345/138 WR,914.36,31.0,0.00,0.00,2017-10-18 08:00:00-05:00,2017-10-31 15:00:00-05:00,LN ELPA 138KV - 59TH 138KV,SPP
170,"59TH ELPAMURR13_1 A LN,59TH,138.0,ELPA,138.0",WR:ROSE WILDPLNS:345:1:10,"ELPAMURR13_1A_LN@59TH<24385>,TMP843_32901,TP12...",LN 59TH 138KV - ELPA 138KV (59TH ELPAMURR13_1 ...,WR:ROSE WILDPLNS:345:1:10,634.40,7.0,5325.56,21.08,2025-12-11 04:00:00-06:00,2026-04-10 05:10:00-05:00,LN 59TH 138KV - ELPA 138KV,SPP
181,"59TH ELPAMURR13_1 B LN,MURR,138.0,59TH,138.0",TEMP MULTI WDRNG1 - SONR1 345 OKGE,ELPAMURR13_1B_LN@59TH<CON3078>,LN MURR 138KV - 59TH 138KV (59TH ELPAMURR13_1 ...,TEMP MULTI WDRNG1 - SONR1 345 OKGE,573.61,9.0,0.00,0.00,2019-12-05 20:00:00-06:00,2019-12-09 14:00:00-06:00,LN MURR 138KV - 59TH 138KV,SPP
176,"59TH ELPAMURR13_1 A LN,ELPA,138.0,59TH,138.0",XF WICH WICH_12 345/138 WR,ELPAMURR13_1A_LN@59TH<CON1840>,LN ELPA 138KV - 59TH 138KV (59TH ELPAMURR13_1 ...,XF WICH WICH_12 345/138 WR,388.03,13.0,0.00,0.00,2017-11-27 13:00:00-06:00,2017-11-29 08:00:00-06:00,LN ELPA 138KV - 59TH 138KV,SPP
165,"59TH ELPAMURR13_1 A LN,59TH,138.0,ELPA,138.0",DBL WICH - BENT 345 WR,ELPAMURR13_1A_LN@59TH<CON9945>,LN 59TH 138KV - ELPA 138KV (59TH ELPAMURR13_1 ...,DBL WICH - BENT 345 WR,40.84,2.0,0.00,0.00,2022-10-23 09:00:00-05:00,2022-10-23 12:00:00-05:00,LN 59TH 138KV - ELPA 138KV,SPP
178,"59TH ELPAMURR13_1 B LN,59TH,138.0,MURR,138.0",LN MED-LD1 - HARPER1 138kV SECI,ELPAMURR13_1B_LN@59TH<CON580>,LN 59TH 138KV - MURR 138KV (59TH ELPAMURR13_1 ...,LN MED-LD1 - HARPER1 138kV SECI,23.32,1.0,0.00,0.00,2014-02-03 23:00:00-06:00,2014-02-03 23:00:00-06:00,LN 59TH 138KV - MURR 138KV,SPP
174,"59TH ELPAMURR13_1 A LN,ELPA,138.0,59TH,138.0",LN WOLF - WAVERLY7 345 WR,TMP838_29609,LN ELPA 138KV - 59TH 138KV (59TH ELPAMURR13_1 ...,LN WOLF - WAVERLY7 345 WR,0.00,0.0,391.14,0.58,2024-06-03 12:55:00-05:00,2024-06-04 08:05:00-05:00,LN ELPA 138KV - 59TH 138KV,SPP
179,"59TH ELPAMURR13_1 B LN,59TH,138.0,MURR,138.0",LN SIDNEY - OGALALA 230 NPPD,TEMP40_21948,LN 59TH 138KV - MURR 138KV (59TH ELPAMURR13_1 ...,LN SIDNEY - OGALALA 230 NPPD,0.00,0.0,0.00,0.00,2016-07-01 00:05:00-05:00,2016-07-01 03:10:00-05:00,LN 59TH 138KV - MURR 138KV,SPP

In [ ]:
def plot_outage_decomposition(df):
    df["newlegend"] = df["hypercluster_uid"].str.replace(",",",\n").apply(lambda x:x[:35])
    fig = px.area(df, x="timestamp", y="impact", color="newlegend", line_group="newlegend")    
    fig.show()


outage_decomp = get_outage_decomposition(mon_uid, con_uid,start_dte, end_dte)
plot_outage_decomposition(outage_decomp)

https://api1.marginalunit.com/reflow/spp-se/constraint/outage_decomposition

In [106]:
display(outage_decomp.head(2))

,timestamp,outage_cluster_uid,impact,hypercluster_uid,newlegend
0,2025-01-13T11:00:00-06:00,WR_SMKHL 9990 A LN,27.13,WR_SMKHL 9990 A LN,WR_SMKHL 9990 A LN
1,2025-01-13T23:00:00-06:00,WR_SMKHL 9990 A LN,-48.26,WR_SMKHL 9990 A LN,WR_SMKHL 9990 A LN

In [13]:
def get_constraint_flow(mon_uid, con_uid, start_dt, end_dt):
    path_ = f"/spp-se/constraint/flow"
    payload = {"collection" : "spp-se",
              "monitored_uid" : mon_uid,
              "contingency_uid" : con_uid,
              "start_datetime" : start_dt,
              "end_datetime" : end_dt}
    return _get_panorama_data("reflow", path_, requests.get, payload)
flow = get_constraint_flow(mon_uid, con_uid, start_dte, end_dte)
display(flow.head(2))
fig = px.area(flow, x="timestamp", y="constraint_flow")    
fig.show()

https://api1.marginalunit.com/reflow/spp-se/constraint/flow

                   timestamp  constraint_flow
0  2025-01-01T05:00:00-06:00            26.49
1  2025-01-01T11:00:00-06:00            34.57

In [16]:
def get_driver_decomp(mon_uid, con_uid, start_dt, end_dt, driver_type):
    path_ = f"/spp-se/constraint/driver_decomposition"
    payload = {"collection" : "spp-se",
              "monitored_uid" : mon_uid,
              "contingency_uid" : con_uid,
              "start_datetime" : start_dt,
              "end_datetime" : end_dt,
              "driver_type" : driver_type}
    return _get_panorama_data("reflow", path_, requests.get, payload)

#Get gen, zonal load and fuel decomposition here
gen_decomp = get_driver_decomp(mon_uid, con_uid, start_dte, end_dte,"GENERATION")
display(gen_decomp.head(10))
load_decomp = get_driver_decomp(mon_uid, con_uid, start_dte, end_dte,"LOAD_ZONE")
display(load_decomp.head(2))
fuel_decomp = get_driver_decomp(mon_uid, con_uid, start_dte, end_dte,"FUEL")
display(fuel_decomp.head(2))

https://api1.marginalunit.com/reflow/spp-se/constraint/driver_decomposition

                   timestamp                         driver_uid  impact
0  2025-01-01T05:00:00-06:00  CROSSRDS 345 RJ1 SAGAMORE_WIND UN -12.275
1  2025-01-01T05:00:00-06:00                 CUNNSUB 19 68 2 UN -19.128
2  2025-01-01T05:00:00-06:00         HOBBS 115 CT2 HOBBS_CT2 UN -18.913
3  2025-01-01T05:00:00-06:00         HOBBS 230 ST1 HOBBS_ST1 UN -22.682
4  2025-01-01T05:00:00-06:00   LOSTDRAW 115 WC1 WILDCAT_WIND UN -14.205
5  2025-01-01T05:00:00-06:00                MSTNG 13.8 71G 2 UN -23.261
6  2025-01-01T05:00:00-06:00                MSTNG 13.8 72G 1 UN -22.950
7  2025-01-01T11:00:00-06:00                 CUNNSUB 19 68 2 UN -18.254
8  2025-01-01T11:00:00-06:00         HOBBS 115 CT2 HOBBS_CT2 UN -18.843
9  2025-01-01T11:00:00-06:00         HOBBS 230 ST1 HOBBS_ST1 UN -23.196

https://api1.marginalunit.com/reflow/spp-se/constraint/driver_decomposition

                   timestamp driver_uid  impact
0  2025-01-01T05:00:00-06:00     CE  CE -12.124
1  2025-01-01T05:00:00-06:00   CSW CSWS  -9.688

https://api1.marginalunit.com/reflow/spp-se/constraint/driver_decomposition

                   timestamp driver_uid  impact fuel_type
0  2025-01-01T05:00:00-06:00       Coal  74.586      Coal
1  2025-01-01T05:00:00-06:00      Hydro  13.785     Hydro

In [9]:
#This cell displays gen impact by year month

gen_decomp['mth'] = pd.to_datetime(gen_decomp['timestamp'],utc=True).dt.month
gen_decomp['yr'] = pd.to_datetime(gen_decomp['timestamp'],utc=True).dt.year

display(gen_decomp.head(2))

df_gen = gen_decomp.groupby(['yr','mth','driver_uid']).mean('impact').sort_values(['yr','mth']).reset_index()
display(df_gen.head(2))
df_gen.pivot(index = 'driver_uid', columns = ['yr','mth'], values = 'impact').round(0)

,timestamp,driver_uid,impact,mth,yr
0,2025-01-01T05:00:00-06:00,CROSSRDS 345 RJ1 SAGAMORE_WIND UN,-12.275,1,2025
1,2025-01-01T05:00:00-06:00,CUNNSUB 19 68 2 UN,-19.128,1,2025

     yr  mth                         driver_uid     impact
0  2025    1  CROSSRDS 345 RJ1 SAGAMORE_WIND UN -19.259099
1  2025    1                 CUNNSUB 19 68 2 UN -13.679878

yr                                 2025                                      \
mth                                  1     2     3     4     5     6     7
driver_uid
CROSSRDS 345 RJ1 SAGAMORE_WIND UN -19.0 -19.0 -23.0 -26.0 -21.0 -20.0 -17.0
CUNNSUB 19 68 2 UN                -14.0 -16.0   NaN -16.0 -19.0 -18.0   NaN
HOBBS 115 CT2 HOBBS_CT2 UN        -18.0 -19.0 -19.0 -20.0 -20.0 -16.0 -17.0
HOBBS 230 ST1 HOBBS_ST1 UN        -20.0 -22.0 -23.0 -25.0 -18.0 -17.0 -18.0
LOSTDRAW 115 WC1 WILDCAT_WIND UN  -18.0 -15.0 -13.0 -15.0 -17.0 -14.0 -13.0
MSTNG 13.8 102G 5 UN              -15.0 -15.0 -14.0 -19.0 -16.0 -16.0 -16.0
MSTNG 13.8 71G 2 UN               -22.0 -25.0 -22.0 -23.0 -22.0 -21.0 -21.0
MSTNG 13.8 72G 1 UN               -23.0 -25.0 -22.0 -23.0 -22.0 -21.0 -21.0
MSTNG 230 BL3 6_GSEC UN           -15.0 -15.0 -17.0 -20.0 -16.0 -17.0 -18.0

yr                                                               2026        \
mth                                  8     9     10    11    12    1     2
driver_uid
CROSSRDS 345 RJ1 SAGAMORE_WIND UN -19.0 -18.0 -18.0 -23.0 -23.0 -21.0 -25.0
CUNNSUB 19 68 2 UN                -19.0 -18.0 -16.0 -19.0 -20.0 -20.0 -21.0
HOBBS 115 CT2 HOBBS_CT2 UN        -19.0 -18.0 -16.0 -20.0 -19.0 -20.0   NaN
HOBBS 230 ST1 HOBBS_ST1 UN        -22.0 -20.0 -14.0 -18.0 -18.0 -24.0 -11.0
LOSTDRAW 115 WC1 WILDCAT_WIND UN  -14.0 -14.0 -15.0 -16.0 -18.0 -19.0 -21.0
MSTNG 13.8 102G 5 UN              -18.0 -18.0 -15.0 -19.0 -19.0 -20.0 -22.0
MSTNG 13.8 71G 2 UN               -22.0 -21.0 -18.0 -23.0 -24.0 -24.0 -26.0
MSTNG 13.8 72G 1 UN               -22.0 -22.0 -19.0 -23.0 -24.0 -24.0 -26.0
MSTNG 230 BL3 6_GSEC UN           -19.0 -13.0 -14.0 -17.0 -18.0 -15.0 -19.0

yr
mth                                  3
driver_uid
CROSSRDS 345 RJ1 SAGAMORE_WIND UN -22.0
CUNNSUB 19 68 2 UN                  NaN
HOBBS 115 CT2 HOBBS_CT2 UN        -19.0
HOBBS 230 ST1 HOBBS_ST1 UN        -23.0
LOSTDRAW 115 WC1 WILDCAT_WIND UN  -18.0
MSTNG 13.8 102G 5 UN              -17.0
MSTNG 13.8 71G 2 UN               -22.0
MSTNG 13.8 72G 1 UN                 NaN
MSTNG 230 BL3 6_GSEC UN           -17.0

In [13]:
fuel_decomp[['fuel_type','impact']].groupby('fuel_type').sum()

                 impact
fuel_type
Coal         165753.648
Hydro         32864.552
Natural Gas -110272.234
Nuclear       98932.727
Solar         -2584.080
Wind           4476.135

In [113]:
load_decomp['mth'] = pd.to_datetime(load_decomp['timestamp'],utc=True).dt.month
load_decomp['yr'] = pd.to_datetime(load_decomp['timestamp'],utc=True).dt.year
df_load = load_decomp[['driver_uid','yr','mth','impact']].groupby(['driver_uid','yr','mth']).sum().reset_index()
df_load.pivot(index = 'driver_uid', columns = ['yr','mth'], values = 'impact').round(0)

yr            2025                                                      \
mth             1        2       3        4        5        6       7
driver_uid
CE  CE         1.0   2390.0 -1896.0  -3886.0  -3112.0  -1707.0  -792.0
CSW CSWS    1290.0  -1692.0  3965.0   6133.0   5377.0   4612.0  3520.0
EES EES     3591.0    -47.0  9377.0  12322.0  12165.0  10082.0  8340.0
Misc        3158.0  14414.0 -6619.0 -15390.0  -9629.0   -417.0  5731.0
NPP NPPD   -3557.0  -1323.0 -8432.0  -9554.0  -9342.0  -8154.0 -9462.0
NSP NSP    -2397.0    166.0 -6669.0  -8262.0  -7659.0  -6892.0 -6138.0
OKG OKGE     590.0  -2883.0  3419.0   5814.0   4680.0   3558.0  2005.0
SOU SOUC    3511.0   1816.0  9421.0  10198.0  10873.0   8297.0  6760.0
SPS SPS    -4715.0 -12293.0 -2528.0   3948.0  -1455.0  -5474.0 -5774.0
WAU WAUE   -3017.0      NaN -8214.0  -9713.0  -8538.0  -7115.0 -6404.0

yr                                                      2026
mth              8       9       10      11      12       1        2       3
driver_uid
CE  CE       -581.0  -423.0  -974.0 -1322.0   -90.0  -3612.0  -3764.0  -533.0
CSW CSWS     3476.0  2482.0  2338.0  3021.0  2594.0   7400.0   5895.0  1854.0
EES EES      8932.0  7330.0  6019.0  8080.0  7363.0  13885.0  11046.0  4523.0
Misc         4779.0  2827.0    97.0  -817.0  1769.0 -15665.0 -17302.0   341.0
NPP NPPD   -10622.0 -7190.0 -5338.0 -7346.0 -7814.0 -11572.0  -8354.0 -4149.0
NSP NSP     -6055.0 -5630.0 -4937.0 -6192.0 -5673.0 -10442.0  -8543.0 -3309.0
OKG OKGE     2052.0  1234.0  1809.0  2249.0  1418.0   6326.0   5721.0  1302.0
SOU SOUC     7373.0  6774.0  5983.0  8230.0  7447.0  11287.0   9294.0  4713.0
SPS SPS     -6073.0 -5144.0 -3468.0 -4096.0 -4852.0   2401.0   4704.0 -3176.0
WAU WAUE    -7076.0 -6575.0 -5673.0 -7622.0 -7407.0 -12062.0  -9100.0 -4102.0